apiVersion: v1
kind: ConfigMap
metadata:
  name: dodo-helm-tutorial-config
data:
  {{ if or (eq .Values.env "prod") (eq .Values.env "dev") }}
  SENTRY__DSN: https://sentry.io/
  {{ end }}
  {{ range $index, $origin := .Values.web.crossOrigins }}
  WEB__CROSS_ORIGIN__{{ $index }}: {{ $origin }}
  {{ end }}
