apiVersion: apps/v1
kind: Deployment
metadata:
  name: dodo-helm-tutorial-web
  labels:
    app.kubernetes.io/name: dodo-helm-tutorial-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: web-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: dodo-helm-tutorial-web
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dodo-helm-tutorial-web
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: web-prod
    spec:
      containers:
      - name: dodo-helm-tutorial-web
        image: cristianiivfa2022/python-ping:latest
        ports:
        - name: http
          containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "25m"
          limits:
            memory: "384Mi"
            cpu: "250m"
        # imagePullPolicy: Never