apiVersion: v1
kind: Service
metadata:
  name: dodo-helm-tutorial-web
  labels:
    app.kubernetes.io/name: dodo-helm-tutorial-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: web-prod
spec:
  selector:
    app.kubernetes.io/name: dodo-helm-tutorial-web
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: web
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer